"""add post announcement field

Revision ID: 746e695fccc2
Revises: 2d36b0add6ba
Create Date: 2025-12-03 19:06:49.125640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746e695fccc2'
down_revision = '2d36b0add6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_announcement', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_announcement')

    # ### end Alembic commands ###
